# Generated by Django 4.1.5 on 2023-02-03 08:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0002_alter_client_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='commande_attribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashbord.commande'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='date_attribution',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attribution',
            name='gestionnaire_attribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashbord.gestionnaire'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='livreur_livraison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashbord.livreur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client_commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashbord.client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commande',
            name='designantion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='nombreSachet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='commande_livraison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashbord.commande'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='etat',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='livreur_livraison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashbord.livreur'),
        ),
    ]
