# Generated by Django 4.1.5 on 2023-02-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0003_attribution_commande_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='commentaire',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
