# Generated by Django 4.1.5 on 2023-02-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0004_attribution_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='designantion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
