# Generated by Django 4.1.7 on 2023-03-15 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashbord', '0005_attribution_designantion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribution',
            old_name='date_attribution',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='attribution',
            old_name='gestionnaire_attribution',
            new_name='gestionnaire',
        ),
        migrations.RenameField(
            model_name='attribution',
            old_name='livreur_livraison',
            new_name='livreur',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='designantion',
            new_name='designation',
        ),
        migrations.AddField(
            model_name='livreur',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
