# Generated by Django 4.1.7 on 2023-03-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0006_rename_date_attribution_attribution_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
