# Generated by Django 4.1.7 on 2023-03-16 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0007_alter_livreur_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_commande',
        ),
        migrations.AddField(
            model_name='commande',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 14, 48, 28, 794818)),
        ),
        migrations.AddField(
            model_name='commande',
            name='poids',
            field=models.FloatField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='prix',
            field=models.FloatField(max_length=12, null=True),
        ),
    ]
