# Generated by Django 4.1.7 on 2023-03-16 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0008_remove_commande_date_commande_commande_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='client_commande',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 15, 21, 34, 304188)),
        ),
    ]
