# Generated by Django 4.1.7 on 2023-03-16 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0012_commande_created_commande_updated_livraison_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 16, 23, 7, 4, 345914)),
        ),
    ]
