# Generated by Django 4.1.7 on 2023-03-17 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0013_alter_commande_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribution',
            old_name='commande_attribution',
            new_name='commande',
        ),
        migrations.RenameField(
            model_name='attribution',
            old_name='designantion',
            new_name='designation',
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 7, 45, 13, 670737)),
        ),
    ]
