# Generated by Django 4.1.7 on 2023-03-17 08:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0015_alter_attribution_commande_alter_commande_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 8, 25, 51, 50392)),
        ),
    ]
