# Generated by Django 4.1.7 on 2023-03-24 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0016_client_created_client_updated_alter_commande_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='gestionnaire',
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 24, 22, 13, 18, 844887)),
        ),
    ]
