# Generated by Django 4.1.7 on 2023-03-27 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0017_remove_attribution_gestionnaire_alter_commande_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='commande_livraison',
            new_name='commande',
        ),
        migrations.RenameField(
            model_name='livraison',
            old_name='livreur_livraison',
            new_name='livreur',
        ),
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 27, 8, 41, 39, 832318)),
        ),
    ]
