# Generated by Django 4.1.7 on 2023-03-28 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0018_rename_commande_livraison_livraison_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 28, 20, 44, 8, 645267)),
        ),
    ]
